const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const canvas=$('#canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
let source=null, processed=null, bgMode='keep', scale=1, offX=0,offY=0,drag=false,lastX=0,lastY=0,sampling=false;
const state=()=>({cols:+$('#cols').value||1,rows:+$('#rows').value||1});
function setCanvasSize(){const wrap=$('#stageWrap');let w=Math.min(900,Math.max(300,wrap.clientWidth-50)),h=Math.min(650,Math.max(300,wrap.clientHeight-50));const ratio=$('#ratio').value;if(ratio!=='auto'){const r=+ratio,gr=(state().cols/state().rows)*r;if(w/h>gr)w=h*gr;else h=w/gr}canvas.width=Math.round(w);canvas.height=Math.round(h);draw()}
function currentImage(){return processed||source}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const im=currentImage();if(!im)return;const w=im.width*scale,h=im.height*scale;ctx.drawImage(im,offX,offY,w,h);const {cols,rows}=state();ctx.save();ctx.strokeStyle='rgba(139,92,246,.95)';ctx.lineWidth=1.5;for(let c=0;c<=cols;c++){let x=c*canvas.width/cols;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let r=0;r<=rows;r++){let y=r*canvas.height/rows;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}ctx.restore()}
function fit(){if(!source)return;const im=currentImage();scale=Math.min(canvas.width/im.width,canvas.height/im.height);offX=(canvas.width-im.width*scale)/2;offY=(canvas.height-im.height*scale)/2;$('#zoom').value=100;$('#zoomLabel').textContent='100%';draw()}
$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{source=im;processed=null;canvas.style.display='block';$('#empty').classList.add('hidden');$('#fileInfo').classList.remove('hidden');$('#fileInfo').textContent=`${f.name} • ${im.width}×${im.height}px`;$('#exportZip').disabled=$('#exportSheet').disabled=false;setCanvasSize();fit();if(bgMode==='remove')removeBg();URL.revokeObjectURL(u)};im.src=u};
$$('[data-bg]').forEach(b=>b.onclick=()=>{$$('[data-bg]').forEach(x=>x.classList.remove('active'));b.classList.add('active');bgMode=b.dataset.bg;$('#bgTools').classList.toggle('hidden',bgMode!=='remove');if(bgMode==='remove')removeBg();else{processed=null;draw()}});
function removeBg(){if(!source)return;const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(source,0,0);const d=x.getImageData(0,0,c.width,c.height),rgb=hex($('#bgColor').value),t=+$('#tolerance').value;for(let i=0;i<d.data.length;i+=4){const dist=Math.hypot(d.data[i]-rgb[0],d.data[i+1]-rgb[1],d.data[i+2]-rgb[2]);if(dist<t)d.data[i+3]=0;else if(dist<t+30)d.data[i+3]=Math.round(d.data[i+3]*(dist-t)/30)}x.putImageData(d,0,0);const im=new Image();im.onload=()=>{processed=im;draw()};im.src=c.toDataURL('image/png')}
function hex(h){return[h.slice(1,3),h.slice(3,5),h.slice(5,7)].map(x=>parseInt(x,16))}
$('#tolerance').oninput=e=>{$('#tolOut').textContent=e.target.value;removeBg()};$('#bgColor').oninput=removeBg;$('#sampleBtn').onclick=()=>{sampling=true;$('#sampleBtn').textContent='Clique no fundo…'};
function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{if(sampling){const p=pos(e),im=currentImage(),ix=Math.floor((p.x-offX)/scale),iy=Math.floor((p.y-offY)/scale);if(ix>=0&&iy>=0&&ix<im.width&&iy<im.height){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const z=c.getContext('2d');z.drawImage(source,0,0);const q=z.getImageData(ix,iy,1,1).data;$('#bgColor').value='#'+[q[0],q[1],q[2]].map(v=>v.toString(16).padStart(2,'0')).join('');sampling=false;$('#sampleBtn').textContent='Pegar cor na imagem';removeBg()}return}drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect();offX+=(e.clientX-lastX)*canvas.width/r.width;offY+=(e.clientY-lastY)*canvas.height/r.height;lastX=e.clientX;lastY=e.clientY;draw()});canvas.addEventListener('pointerup',()=>drag=false);
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e),old=scale,f=e.deltaY<0?1.08:.92;scale=Math.max(.02,Math.min(20,scale*f));offX=p.x-(p.x-offX)*(scale/old);offY=p.y-(p.y-offY)*(scale/old);draw()},{passive:false});
$('#zoom').oninput=e=>{if(!source)return;const im=currentImage(),base=Math.min(canvas.width/im.width,canvas.height/im.height),cx=canvas.width/2,cy=canvas.height/2,old=scale;scale=base*(+e.target.value/100);offX=cx-(cx-offX)*(scale/old);offY=cy-(cy-offY)*(scale/old);$('#zoomLabel').textContent=e.target.value+'%';draw()};
['cols','rows','ratio'].forEach(id=>$('#'+id).onchange=()=>{if(id==='ratio')setCanvasSize();else draw()});$$('[data-grid]').forEach(b=>b.onclick=()=>{const [c,r]=b.dataset.grid.split(',');$('#cols').value=c;$('#rows').value=r;$$('[data-grid]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});$('#fitBtn').onclick=fit;
function renderClean(){const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const x=c.getContext('2d');const im=currentImage();x.drawImage(im,offX,offY,im.width*scale,im.height*scale);return c}
function blob(c,type='image/png'){return new Promise(ok=>c.toBlob(ok,type,type==='image/webp'?.95:undefined))}
$('#exportZip').onclick=async()=>{if(!source)return;const btn=$('#exportZip'),old=btn.textContent;btn.disabled=true;btn.textContent='Gerando ZIP…';try{const zip=new JSZip(),clean=renderClean(),{cols,rows}=state(),cw=clean.width/cols,ch=clean.height/rows,fmt=$('#format').value,mime=fmt==='webp'?'image/webp':'image/png';let n=1;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const out=document.createElement('canvas');out.width=Math.round(cw);out.height=Math.round(ch);out.getContext('2d').drawImage(clean,c*cw,r*ch,cw,ch,0,0,out.width,out.height);zip.file(`recorte-${String(n++).padStart(3,'0')}.${fmt}`,await blob(out,mime))}save(await zip.generateAsync({type:'blob'}),'recortes.zip')}finally{btn.disabled=false;btn.textContent=old}};
$('#exportSheet').onclick=async()=>save(await blob(renderClean(),'image/png'),'sprite-sheet.png');
function save(b,name){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#resetBtn').onclick=()=>location.reload();window.addEventListener('resize',()=>{if(source)setCanvasSize()});