(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#canvas'),stage=$('#stageWrap');if(!canvas||!stage)return;
const oldOverlay=$('#cropOverlay');if(oldOverlay)oldOverlay.style.display='none';
const style=document.createElement('style');style.textContent=`
.cropEditorLayer{position:absolute;z-index:45;display:none;touch-action:none;user-select:none;-webkit-user-select:none;overflow:hidden}
.cropEditorSurface{position:absolute;inset:0;width:100%;height:100%;display:block;touch-action:none;user-select:none;-webkit-user-select:none}
.cropSelection{position:absolute;display:none;border:2px solid #f5f3ff;box-shadow:0 0 0 9999px rgba(3,5,10,.57),0 0 0 1px #8b5cf6 inset;touch-action:none;cursor:move}
.cropSelection:before{content:'';position:absolute;inset:-1px;border:1px dashed rgba(167,139,250,.85);pointer-events:none}
.cropHandle{position:absolute;width:26px;height:26px;touch-action:none}
.cropHandle:after{content:'';position:absolute;left:50%;top:50%;width:11px;height:11px;transform:translate(-50%,-50%);border-radius:4px;background:#fff;border:2px solid #7c3aed;box-shadow:0 2px 10px #000a}
.cropHandle[data-dir=n]{left:50%;top:0;transform:translate(-50%,-50%);cursor:n-resize}.cropHandle[data-dir=s]{left:50%;bottom:0;transform:translate(-50%,50%);cursor:s-resize}
.cropHandle[data-dir=e]{right:0;top:50%;transform:translate(50%,-50%);cursor:e-resize}.cropHandle[data-dir=w]{left:0;top:50%;transform:translate(-50%,-50%);cursor:w-resize}
.cropHandle[data-dir=nw]{left:0;top:0;transform:translate(-50%,-50%);cursor:nw-resize}.cropHandle[data-dir=ne]{right:0;top:0;transform:translate(50%,-50%);cursor:ne-resize}
.cropHandle[data-dir=sw]{left:0;bottom:0;transform:translate(-50%,50%);cursor:sw-resize}.cropHandle[data-dir=se]{right:0;bottom:0;transform:translate(50%,50%);cursor:se-resize}
.cropSizeBadge{position:absolute;left:50%;top:-31px;transform:translateX(-50%);padding:5px 8px;border-radius:7px;background:#0d0f17e8;border:1px solid #4c2d72;color:#e9ddff;font:700 9px/1 system-ui;white-space:nowrap;pointer-events:none}
@media(max-width:800px){.cropHandle{width:34px;height:34px}.cropHandle:after{width:13px;height:13px;border-radius:50%}.cropSizeBadge{top:-35px;font-size:10px}}
`;document.head.appendChild(style);
const layer=document.createElement('div');layer.className='cropEditorLayer';
const surface=document.createElement('canvas');surface.className='cropEditorSurface';
const selection=document.createElement('div');selection.className='cropSelection';
const badge=document.createElement('span');badge.className='cropSizeBadge';selection.appendChild(badge);
['n','s','e','w','nw','ne','sw','se'].forEach(dir=>{const h=document.createElement('span');h.className='cropHandle';h.dataset.dir=dir;selection.appendChild(h)});
layer.append(surface,selection);stage.appendChild(layer);
let active=false,box=null,action=null,pointerId=null,startPoint=null,startBox=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function status(t){const e=$('#cropStatus');if(e){e.classList.remove('hidden');e.textContent=t}}
function emit(on){window.__recorteCropActive=on;window.dispatchEvent(new CustomEvent('recorte-crop-mode',{detail:{active:on}}))}
function syncLayer(){if(!active)return;const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect();layer.style.left=(cr.left-sr.left+stage.scrollLeft)+'px';layer.style.top=(cr.top-sr.top+stage.scrollTop)+'px';layer.style.width=cr.width+'px';layer.style.height=cr.height+'px';surface.width=Math.max(1,canvas.width);surface.height=Math.max(1,canvas.height);const view=window.recorteSplit?.renderViewCanvas?.(1);const x=surface.getContext('2d');x.clearRect(0,0,surface.width,surface.height);if(view)x.drawImage(view,0,0,surface.width,surface.height);drawBox()}
function point(e){const r=layer.getBoundingClientRect();return{x:clamp((e.clientX-r.left)*canvas.width/Math.max(1,r.width),0,canvas.width),y:clamp((e.clientY-r.top)*canvas.height/Math.max(1,r.height),0,canvas.height)}}
function drawBox(){if(!active||!box){selection.style.display='none';return}const r=layer.getBoundingClientRect(),sx=r.width/canvas.width,sy=r.height/canvas.height;selection.style.display='block';selection.style.left=(box.x*sx)+'px';selection.style.top=(box.y*sy)+'px';selection.style.width=Math.max(1,box.w*sx)+'px';selection.style.height=Math.max(1,box.h*sy)+'px';badge.textContent=`${Math.round(box.w)} × ${Math.round(box.h)}`}
function valid(){return box&&box.w>=8&&box.h>=8}
function setApply(){const b=$('#cropApply');if(b)b.disabled=!valid()}
function begin(){if(!window.recorteSplit?.getCurrent?.())return;active=true;box=null;action=null;pointerId=null;layer.style.display='block';$('#cropStart').textContent='Cancelar recorte';$('#cropApply').disabled=true;emit(true);syncLayer();status('Arraste para criar o recorte. Depois ajuste pelas bordas/cantos ou mova a seleção sem precisar refazer.');}
function end(cancelText=false){active=false;box=null;action=null;pointerId=null;selection.style.display='none';layer.style.display='none';$('#cropStart').textContent='✂ Recortar';$('#cropApply').disabled=true;emit(false);window.recorteSplit?.redraw?.();if(cancelText)status('Recorte cancelado.')}
$('#cropStart')?.addEventListener('click',()=>active?end(true):begin());
layer.addEventListener('pointerdown',e=>{if(!active)return;const handle=e.target.closest?.('.cropHandle');const inside=e.target.closest?.('.cropSelection');pointerId=e.pointerId;startPoint=point(e);startBox=box?{...box}:null;if(handle&&box){action='resize:'+handle.dataset.dir}else if(inside&&box){action='move'}else{action='new';box={x:startPoint.x,y:startPoint.y,w:0,h:0}}layer.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopPropagation()},{capture:true});
layer.addEventListener('pointermove',e=>{if(!active||e.pointerId!==pointerId||!action)return;const q=point(e),dx=q.x-startPoint.x,dy=q.y-startPoint.y,min=12;if(action==='new'){box={x:Math.min(startPoint.x,q.x),y:Math.min(startPoint.y,q.y),w:Math.abs(q.x-startPoint.x),h:Math.abs(q.y-startPoint.y)}}else if(action==='move'&&startBox){box={...startBox,x:clamp(startBox.x+dx,0,canvas.width-startBox.w),y:clamp(startBox.y+dy,0,canvas.height-startBox.h)}}else if(action.startsWith('resize:')&&startBox){const dir=action.slice(7);let x0=startBox.x,y0=startBox.y,x1=startBox.x+startBox.w,y1=startBox.y+startBox.h;if(dir.includes('w'))x0=clamp(startBox.x+dx,0,x1-min);if(dir.includes('e'))x1=clamp(startBox.x+startBox.w+dx,x0+min,canvas.width);if(dir.includes('n'))y0=clamp(startBox.y+dy,0,y1-min);if(dir.includes('s'))y1=clamp(startBox.y+startBox.h+dy,y0+min,canvas.height);box={x:x0,y:y0,w:x1-x0,h:y1-y0}}drawBox();setApply();e.preventDefault();e.stopPropagation()},{capture:true});
function pointerEnd(e){if(!active||e.pointerId!==pointerId)return;pointerId=null;action=null;startPoint=null;startBox=null;setApply();if(valid())status(`Seleção pronta: ${Math.round(box.w)} × ${Math.round(box.h)}. Ajuste pelas alças se precisar e toque em Aplicar recorte.`);e.preventDefault();e.stopPropagation()}
layer.addEventListener('pointerup',pointerEnd,{capture:true});layer.addEventListener('pointercancel',pointerEnd,{capture:true});
$('#cropApply')?.addEventListener('click',()=>{if(!valid()||!window.recorteSplit?.renderViewCanvas)return;const view=window.recorteSplit.getViewState?.()||{},nativeScale=Math.max(1,Math.min(4,Math.max((view.imageWidth||canvas.width)/Math.max(1,canvas.width),(view.imageHeight||canvas.height)/Math.max(1,canvas.height)))),full=window.recorteSplit.renderViewCanvas(nativeScale),sx=Math.round(box.x*nativeScale),sy=Math.round(box.y*nativeScale),sw=Math.max(1,Math.round(box.w*nativeScale)),sh=Math.max(1,Math.round(box.h*nativeScale)),c=document.createElement('canvas');c.width=Math.min(sw,Math.max(1,full.width-sx));c.height=Math.min(sh,Math.max(1,full.height-sy));const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.drawImage(full,sx,sy,c.width,c.height,0,0,c.width,c.height);const out=new Image();out.onload=()=>{window.recorteSplit.setAIResult(out);status(`Recorte aplicado: ${c.width} × ${c.height}px.`);end(false)};out.onerror=()=>status('Não foi possível aplicar o recorte. Tente novamente.');out.src=c.toDataURL('image/png')});
window.addEventListener('resize',()=>requestAnimationFrame(syncLayer));stage.addEventListener('scroll',()=>requestAnimationFrame(syncLayer));window.addEventListener('scroll',()=>requestAnimationFrame(syncLayer),true);
})();