(()=>{'use strict';
const $=s=>document.querySelector(s),stage=$('#stageWrap'),canvas=$('#canvas');if(!stage||!canvas)return;
const style=document.createElement('style');style.textContent=`
.gridHandle{position:absolute;z-index:16;display:none;touch-action:none;user-select:none;-webkit-user-select:none;opacity:.78;transition:opacity .12s ease}.gridHandle.v{width:20px;cursor:col-resize;transform:translateX(-50%)}.gridHandle.h{height:20px;cursor:row-resize;transform:translateY(-50%)}.gridHandle:before{content:'';position:absolute;background:rgba(155,92,255,.72);border-radius:99px;box-shadow:0 0 6px rgba(139,92,246,.2)}.gridHandle.v:before{width:1px;height:100%;left:9px;top:0}.gridHandle.h:before{height:1px;width:100%;top:9px;left:0}.gridHandle:after{content:attr(data-label);position:absolute;width:13px;height:13px;display:grid;place-items:center;border:1px solid rgba(167,139,250,.6);background:rgba(37,19,67,.45);color:#fff;border-radius:4px;font-size:7px;box-shadow:0 3px 9px #0005;backdrop-filter:blur(2px);-webkit-backdrop-filter:blur(2px)}.gridHandle.v:after{left:3px;top:50%;transform:translateY(-50%)}.gridHandle.h:after{top:3px;left:50%;transform:translateX(-50%)}.gridHandle.dragging{opacity:.28}.gridHandle.dragging:after{opacity:.04}.gridHandle.locked{cursor:not-allowed;opacity:.95}.gridHandle.locked:before{background:#a78bfa;box-shadow:0 0 8px #8b5cf666}.gridLineLock{position:absolute;z-index:3;width:20px;height:20px;border-radius:7px;border:1px solid #343a4b;background:#10141d;color:#9ca3af;display:grid;place-items:center;font:700 10px/1 system-ui;box-shadow:0 3px 10px #0007;opacity:.72}.gridHandle.v .gridLineLock{left:17px;top:50%;transform:translateY(-50%)}.gridHandle.h .gridLineLock{top:17px;left:50%;transform:translateX(-50%)}.gridHandle.locked .gridLineLock{background:#281747;border-color:#8b5cf6;color:#ddd6fe;opacity:1}.gridCollisionDot{position:absolute;z-index:21;width:10px;height:10px;border-radius:50%;background:#fb7185;border:2px solid #fff;box-shadow:0 0 0 3px rgba(251,113,133,.28),0 3px 10px #0009;pointer-events:none;transform:translate(-50%,-50%)}.gridCollisionDot:after{content:'!';position:absolute;inset:0;display:grid;place-items:center;color:#5f0716;font:900 7px/1 system-ui}@media(max-width:800px){.gridHandle.v{width:26px}.gridHandle.h{height:26px}.gridHandle.v:before{left:12px}.gridHandle.h:before{top:12px}.gridHandle:after{width:12px;height:12px;font-size:7px;opacity:.44}.gridHandle.v:after{left:6px}.gridHandle.h:after{top:6px}.gridHandle.v .gridLineLock{left:21px}.gridHandle.h .gridLineLock{top:21px}.gridLineLock{width:22px;height:22px}.gridCollisionDot{width:9px;height:9px}}
`;document.head.appendChild(style);
let state={cols:0,rows:0,x:[],y:[]},handles=[],markers=[],drag=null,cropMode=false,sensorTimer=null,locks={x:new Set(),y:new Set()};
const equal=n=>Array.from({length:n+1},(_,i)=>i/n),notify=()=>window.dispatchEvent(new CustomEvent('recorte-grid-change'));
function ensure(cols,rows){cols=Math.max(1,+cols||1);rows=Math.max(1,+rows||1);if(state.cols!==cols||state.x.length!==cols+1){state.cols=cols;state.x=equal(cols);locks.x.clear()}if(state.rows!==rows||state.y.length!==rows+1){state.rows=rows;state.y=equal(rows);locks.y.clear()}return state}
function getLines(axis,count){const s=ensure(+$('#cols')?.value||1,+$('#rows')?.value||1),arr=axis==='x'?s.x:s.y;return arr.length===count+1?arr.slice():equal(count)}
function isLocked(axis,index){return locks[axis]?.has(index)}
function setLine(axis,index,value){if(isLocked(axis,index))return;const s=ensure(+$('#cols')?.value||1,+$('#rows')?.value||1),arr=axis==='x'?s.x:s.y,g=window.recorteSplit?.getGridRect?.();if(!g||index<=0||index>=arr.length-1)return;const pxSize=axis==='x'?g.w:g.h,minNorm=Math.min(.18,Math.max(.018,24/Math.max(1,pxSize))),lo=arr[index-1]+minNorm,hi=arr[index+1]-minNorm;arr[index]=Math.max(lo,Math.min(hi,value));window.recorteSplit?.redraw?.();notify();requestAnimationFrame(update)}
function reset(){const s=ensure(+$('#cols')?.value||1,+$('#rows')?.value||1);s.x=equal(s.cols);s.y=equal(s.rows);locks.x.clear();locks.y.clear();window.recorteSplit?.redraw?.();notify();requestAnimationFrame(rebuild)}
window.recorteGrid={getLines,setLine,reset,ensure,isLocked,toggleLock:(axis,index)=>{isLocked(axis,index)?locks[axis].delete(index):locks[axis].add(index);requestAnimationFrame(update)}};
function clearHandles(){handles.forEach(h=>h.remove());handles=[]}function clearMarkers(){markers.forEach(m=>m.remove());markers=[]}
function toggleLock(axis,index,h){if(isLocked(axis,index))locks[axis].delete(index);else locks[axis].add(index);h.classList.toggle('locked',isLocked(axis,index));const b=h.querySelector('.gridLineLock');if(b){b.textContent=isLocked(axis,index)?'🔒':'🔓';b.title=isLocked(axis,index)?'Linha travada — toque para liberar':'Travar esta linha'}notify()}
function make(axis,index){const h=document.createElement('div');h.className=`gridHandle ${axis==='x'?'v':'h'}`;h.dataset.axis=axis;h.dataset.index=index;h.dataset.label=axis==='x'?'↔':'↕';const lock=document.createElement('button');lock.type='button';lock.className='gridLineLock';lock.textContent=isLocked(axis,index)?'🔒':'🔓';lock.title=isLocked(axis,index)?'Linha travada — toque para liberar':'Travar esta linha';lock.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation()});lock.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();toggleLock(axis,index,h)});h.appendChild(lock);h.classList.toggle('locked',isLocked(axis,index));h.addEventListener('pointerdown',e=>{if(cropMode||isLocked(axis,index)||e.target.closest('.gridLineLock'))return;drag={axis,index,pointerId:e.pointerId};h.classList.add('dragging');h.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopPropagation()});h.addEventListener('pointermove',e=>{if(!drag||drag.pointerId!==e.pointerId)return;const g=window.recorteSplit?.getGridRect?.(),cr=canvas.getBoundingClientRect();if(!g||!cr.width||!cr.height)return;const cx=(e.clientX-cr.left)*canvas.width/cr.width,cy=(e.clientY-cr.top)*canvas.height/cr.height,val=axis==='x'?(cx-g.x)/g.w:(cy-g.y)/g.h;setLine(axis,index,val);e.preventDefault();e.stopPropagation()});const end=e=>{if(!drag)return;drag=null;h.classList.remove('dragging');try{h.releasePointerCapture?.(e.pointerId)}catch{}notify();scheduleSensor();e.preventDefault();e.stopPropagation()};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end);stage.appendChild(h);handles.push(h);return h}
function rebuild(){clearHandles();const cols=Math.max(1,+$('#cols')?.value||1),rows=Math.max(1,+$('#rows')?.value||1);ensure(cols,rows);for(let i=1;i<cols;i++)make('x',i);for(let i=1;i<rows;i++)make('y',i);update()}
function update(){if(cropMode||window.__recorteCropActive||canvas.style.display==='none'||!window.recorteSplit?.getCurrent?.()){handles.forEach(h=>h.style.display='none');clearMarkers();return}const g=window.recorteSplit?.getGridRect?.();if(!g)return;const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),sx=cr.width/canvas.width,sy=cr.height/canvas.height,left=cr.left-sr.left+stage.scrollLeft,top=cr.top-sr.top+stage.scrollTop,xs=getLines('x',g.cols),ys=getLines('y',g.rows);handles.forEach(h=>{const axis=h.dataset.axis,index=+h.dataset.index;h.classList.toggle('locked',isLocked(axis,index));const lock=h.querySelector('.gridLineLock');if(lock)lock.textContent=isLocked(axis,index)?'🔒':'🔓';h.style.display='block';if(axis==='x'){h.style.left=(left+(g.x+g.w*xs[index])*sx)+'px';h.style.top=(top+g.y*sy)+'px';h.style.height=(g.h*sy)+'px'}else{h.style.top=(top+(g.y+g.h*ys[index])*sy)+'px';h.style.left=(left+g.x*sx)+'px';h.style.width=(g.w*sx)+'px'}});scheduleSensor()}
function alphaData(){try{const view=window.recorteSplit?.renderViewCanvas?.(1);if(!view)return null;const x=view.getContext('2d',{willReadFrequently:true}),id=x.getImageData(0,0,view.width,view.height);return{data:id.data,w:view.width,h:view.height}}catch{return null}}
function hitNear(a,axis,pos,start,end){const p=Math.round(pos),lo=Math.max(0,Math.round(start)),hi=Math.min(axis==='x'?a.h:a.w,Math.round(end));let best=null;for(let q=lo;q<hi;q+=2){for(let o=-2;o<=2;o++){const xx=axis==='x'?Math.max(0,Math.min(a.w-1,p+o)):Math.max(0,Math.min(a.w-1,q)),yy=axis==='x'?Math.max(0,Math.min(a.h-1,q)):Math.max(0,Math.min(a.h-1,p+o)),al=a.data[(yy*a.w+xx)*4+3];if(al>28){best={x:xx,y:yy};break}}if(best)break}return best}
function markerAt(x,y){const g=window.recorteSplit?.getGridRect?.(),cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect();if(!g)return;const sx=cr.width/canvas.width,sy=cr.height/canvas.height,left=cr.left-sr.left+stage.scrollLeft,top=cr.top-sr.top+stage.scrollTop,m=document.createElement('span');m.className='gridCollisionDot';m.style.left=(left+x*sx)+'px';m.style.top=(top+y*sy)+'px';stage.appendChild(m);markers.push(m)}
function sensor(){clearMarkers();if(cropMode||!window.recorteSplit?.getCurrent?.()){window.dispatchEvent(new CustomEvent('recorte-grid-collisions',{detail:{frames:[],points:[]}}));return}const a=alphaData(),g=window.recorteSplit?.getGridRect?.();if(!a||!g)return;const xs=getLines('x',g.cols),ys=getLines('y',g.rows),frames=new Set(),points=[];for(let i=1;i<g.cols;i++){const x=g.x+g.w*xs[i];for(let r=0;r<g.rows;r++){const y0=g.y+g.h*ys[r],y1=g.y+g.h*ys[r+1],hit=hitNear(a,'x',x,y0,y1);if(hit){points.push(hit);frames.add(r*g.cols+i);frames.add(r*g.cols+i+1)}}}for(let i=1;i<g.rows;i++){const y=g.y+g.h*ys[i];for(let c=0;c<g.cols;c++){const x0=g.x+g.w*xs[c],x1=g.x+g.w*xs[c+1],hit=hitNear(a,'y',y,x0,x1);if(hit){points.push(hit);frames.add((i-1)*g.cols+c+1);frames.add(i*g.cols+c+1)}}}points.slice(0,48).forEach(p=>markerAt(p.x,p.y));window.dispatchEvent(new CustomEvent('recorte-grid-collisions',{detail:{frames:[...frames].sort((a,b)=>a-b),points}}))}
function scheduleSensor(){clearTimeout(sensorTimer);sensorTimer=setTimeout(sensor,120)}
['cols','rows'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{ensure(+$('#cols')?.value||1,+$('#rows')?.value||1);rebuild();notify()}));document.querySelectorAll('.presets button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{rebuild();notify()},0)));['ratio','ratioW','ratioH','gridGap'].forEach(id=>$('#'+id)?.addEventListener(id==='ratio'?'change':'input',()=>requestAnimationFrame(update)));$('#resetGridLines')?.addEventListener('click',reset);window.addEventListener('resize',()=>requestAnimationFrame(update));stage.addEventListener('scroll',()=>requestAnimationFrame(update));window.addEventListener('recorte-crop-mode',e=>{cropMode=!!e.detail?.active;if(cropMode){handles.forEach(h=>h.style.display='none');clearMarkers()}else requestAnimationFrame(update)});window.addEventListener('recorte-grid-change',scheduleSensor);new MutationObserver(()=>requestAnimationFrame(update)).observe(canvas,{attributes:true,attributeFilter:['style','width','height']});setTimeout(rebuild,250)
})();