(()=>{'use strict';
const $=s=>document.querySelector(s),stage=$('#stageWrap'),canvas=$('#canvas');if(!stage||!canvas)return;
const style=document.createElement('style');style.textContent=`
.gridHandle{position:absolute;z-index:16;display:none;touch-action:none;user-select:none;-webkit-user-select:none;opacity:.9;transition:opacity .15s ease}
.gridHandle.v{width:28px;cursor:col-resize;transform:translateX(-50%)}.gridHandle.h{height:28px;cursor:row-resize;transform:translateY(-50%)}
.gridHandle:before{content:'';position:absolute;background:rgba(155,92,255,.78);box-shadow:0 0 9px rgba(139,92,246,.38);border-radius:99px;transition:background .15s,box-shadow .15s}
.gridHandle.v:before{width:2px;height:100%;left:13px;top:0}.gridHandle.h:before{height:2px;width:100%;top:13px;left:0}
.gridHandle:after{content:attr(data-label);position:absolute;width:18px;height:18px;display:grid;place-items:center;border:1px solid rgba(167,139,250,.9);background:rgba(37,19,67,.78);color:#fff;border-radius:6px;box-shadow:0 5px 14px #0007;font-size:10px;line-height:1;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);transition:opacity .15s,transform .15s,background .15s}
.gridHandle.v:after{left:5px;top:50%;transform:translateY(-50%)}.gridHandle.h:after{top:5px;left:50%;transform:translateX(-50%)}
.gridHandle:hover:after{background:#5b21b6}.gridHandle.dragging:after{opacity:.12}.gridHandle.dragging{opacity:.55}
.gridHandle.collision:before{background:#fb7185;box-shadow:0 0 12px #fb7185aa}.gridHandle.collision:after{border-color:#fb7185;background:rgba(127,29,29,.72)}
.gridHitBadge{position:absolute;z-index:2;display:none;min-width:16px;height:16px;padding:0 4px;place-items:center;border-radius:999px;background:#be123c;color:#fff;border:1px solid #fecdd3;font:800 8px/1 system-ui;box-shadow:0 3px 10px #0009;pointer-events:none}
.gridHandle.collision .gridHitBadge{display:grid}.gridHandle.v .gridHitBadge{left:16px;top:calc(50% - 17px)}.gridHandle.h .gridHitBadge{top:16px;left:calc(50% + 7px)}
.gridAdjustHint{margin-top:10px;padding:9px 10px;border:1px solid #3d2b58;background:#15101f;border-radius:9px;color:#b9aec9;font-size:9px;line-height:1.45}.gridAdjustHint b{color:#e9ddff}
@media(max-width:800px){.gridHandle.v{width:34px}.gridHandle.h{height:34px}.gridHandle.v:before{left:16px}.gridHandle.h:before{top:16px}.gridHandle:after{width:16px;height:16px;font-size:9px;border-radius:5px;opacity:.58}.gridHandle.v:after{left:9px}.gridHandle.h:after{top:9px}.gridHandle.dragging:after{opacity:.06}.gridHandle.collision:after{opacity:.78}}
`;document.head.appendChild(style);
let state={cols:0,rows:0,x:[],y:[]},handles=[],drag=null,cropMode=false,sensorTimer=null,transCache={im:null,value:false};
const equal=n=>Array.from({length:n+1},(_,i)=>i/n),notify=()=>window.dispatchEvent(new CustomEvent('recorte-grid-change'));
function ensure(cols,rows){cols=Math.max(1,+cols||1);rows=Math.max(1,+rows||1);if(state.cols!==cols||state.x.length!==cols+1){state.cols=cols;state.x=equal(cols)}if(state.rows!==rows||state.y.length!==rows+1){state.rows=rows;state.y=equal(rows)}return state}
function getLines(axis,count){const s=ensure(+$('#cols')?.value||1,+$('#rows')?.value||1),arr=axis==='x'?s.x:s.y;if(arr.length!==count+1)return equal(count);return arr.slice()}
function setLine(axis,index,value){const s=ensure(+$('#cols')?.value||1,+$('#rows')?.value||1),arr=axis==='x'?s.x:s.y,g=window.recorteSplit?.getGridRect?.();if(!g||index<=0||index>=arr.length-1)return;const pxSize=axis==='x'?g.w:g.h,minNorm=Math.min(.18,Math.max(.018,24/Math.max(1,pxSize))),lo=arr[index-1]+minNorm,hi=arr[index+1]-minNorm;arr[index]=Math.max(lo,Math.min(hi,value));window.recorteSplit?.redraw?.();notify();requestAnimationFrame(update)}
function reset(){const s=ensure(+$('#cols')?.value||1,+$('#rows')?.value||1);s.x=equal(s.cols);s.y=equal(s.rows);window.recorteSplit?.redraw?.();notify();requestAnimationFrame(update)}
window.recorteGrid={getLines,setLine,reset,ensure};
function clear(){handles.forEach(h=>h.remove());handles=[]}
function make(axis,index){const h=document.createElement('div');h.className=`gridHandle ${axis==='x'?'v':'h'}`;h.dataset.axis=axis;h.dataset.index=index;h.dataset.label=axis==='x'?'↔':'↕';h.title=axis==='x'?'Arraste para ajustar a largura dos cortes':'Arraste para ajustar a altura dos cortes';const badge=document.createElement('span');badge.className='gridHitBadge';h.appendChild(badge);h.addEventListener('pointerdown',e=>{if(cropMode)return;const g=window.recorteSplit?.getGridRect?.();if(!g)return;drag={axis,index,pointerId:e.pointerId};h.classList.add('dragging');h.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopPropagation()});h.addEventListener('pointermove',e=>{if(!drag||drag.pointerId!==e.pointerId)return;const g=window.recorteSplit?.getGridRect?.(),cr=canvas.getBoundingClientRect();if(!g||!cr.width||!cr.height)return;const cx=(e.clientX-cr.left)*canvas.width/cr.width,cy=(e.clientY-cr.top)*canvas.height/cr.height,val=axis==='x'?(cx-g.x)/g.w:(cy-g.y)/g.h;setLine(axis,index,val);e.preventDefault();e.stopPropagation()});const end=e=>{if(!drag)return;drag=null;h.classList.remove('dragging');try{h.releasePointerCapture?.(e.pointerId)}catch{}notify();scheduleSensor();e.preventDefault();e.stopPropagation()};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end);stage.appendChild(h);handles.push(h);return h}
function sourceHasTransparency(){const im=window.recorteSplit?.getSource?.();if(!im)return false;if(transCache.im===im)return transCache.value;let value=false;try{const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height,max=220,s=Math.min(1,max/Math.max(iw,ih)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(iw*s));c.height=Math.max(1,Math.round(ih*s));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data;let transparent=0;for(let i=3;i<d.length;i+=16)if(d[i]<245)transparent++;value=transparent>Math.max(2,d.length/16*.004)}catch{}transCache={im,value};return value}
function countRuns(view,axis,pos,start,end){const x=view.getContext('2d',{willReadFrequently:true}),w=view.width,h=view.height,p=Math.round(pos),a=Math.max(0,Math.round(start)),b=Math.min(axis==='x'?h:w,Math.round(end));if(b<=a)return 0;let runs=0,on=false;const step=Math.max(1,Math.floor((b-a)/420));for(let q=a;q<b;q+=step){let hit=false;for(let o=-2;o<=2&&!hit;o++){const xx=axis==='x'?Math.max(0,Math.min(w-1,p+o)):Math.max(0,Math.min(w-1,q)),yy=axis==='x'?Math.max(0,Math.min(h-1,q)):Math.max(0,Math.min(h-1,p+o));try{hit=x.getImageData(xx,yy,1,1).data[3]>32}catch{}}if(hit&&!on){runs++;on=true}else if(!hit)on=false}return runs}
function sensor(){if(cropMode||!window.recorteSplit?.getCurrent?.()||!sourceHasTransparency()){handles.forEach(h=>{h.classList.remove('collision');const b=h.querySelector('.gridHitBadge');if(b)b.textContent=''});return}const g=window.recorteSplit?.getGridRect?.(),view=window.recorteSplit?.renderViewCanvas?.(1);if(!g||!view)return;const xs=getLines('x',g.cols),ys=getLines('y',g.rows);handles.forEach(h=>{const axis=h.dataset.axis,index=+h.dataset.index,pos=axis==='x'?g.x+g.w*xs[index]:g.y+g.h*ys[index],hits=countRuns(view,axis,pos,axis==='x'?g.y:g.x,axis==='x'?g.y+g.h:g.x+g.w),badge=h.querySelector('.gridHitBadge');h.classList.toggle('collision',hits>0);if(badge)badge.textContent=hits>0?String(hits):'';h.title=hits>0?`⚠ Esta divisão atravessa ${hits} área${hits>1?'s':''} visível${hits>1?'eis':''}. Ajuste antes de exportar.`:(axis==='x'?'Arraste para ajustar a largura dos cortes':'Arraste para ajustar a altura dos cortes')})}
function scheduleSensor(){clearTimeout(sensorTimer);sensorTimer=setTimeout(sensor,140)}
function rebuild(){clear();const cols=Math.max(1,+$('#cols')?.value||1),rows=Math.max(1,+$('#rows')?.value||1);ensure(cols,rows);for(let i=1;i<cols;i++)make('x',i);for(let i=1;i<rows;i++)make('y',i);update()}
function update(){if(cropMode||window.__recorteCropActive||canvas.style.display==='none'||!window.recorteSplit?.getCurrent?.()){handles.forEach(h=>h.style.display='none');return}const g=window.recorteSplit?.getGridRect?.();if(!g)return;const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),sx=cr.width/canvas.width,sy=cr.height/canvas.height,left=cr.left-sr.left+stage.scrollLeft,top=cr.top-sr.top+stage.scrollTop,xs=getLines('x',g.cols),ys=getLines('y',g.rows);handles.forEach(h=>{const axis=h.dataset.axis,index=+h.dataset.index;h.style.display='block';if(axis==='x'){const x=left+(g.x+g.w*xs[index])*sx;h.style.left=x+'px';h.style.top=(top+g.y*sy)+'px';h.style.height=(g.h*sy)+'px'}else{const y=top+(g.y+g.h*ys[index])*sy;h.style.top=y+'px';h.style.left=(left+g.x*sx)+'px';h.style.width=(g.w*sx)+'px'}});scheduleSensor()}
['cols','rows'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{ensure(+$('#cols')?.value||1,+$('#rows')?.value||1);rebuild();notify()}));document.querySelectorAll('.presets button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{rebuild();notify()},0)));['ratio','ratioW','ratioH','gridGap'].forEach(id=>$('#'+id)?.addEventListener(id==='ratio'?'change':'input',()=>requestAnimationFrame(update)));$('#resetGridLines')?.addEventListener('click',reset);$('#masterGrid')?.addEventListener('change',()=>requestAnimationFrame(update));window.addEventListener('resize',()=>requestAnimationFrame(update));stage.addEventListener('scroll',()=>requestAnimationFrame(update));window.addEventListener('recorte-crop-mode',e=>{cropMode=!!e.detail?.active;if(cropMode){handles.forEach(h=>h.style.display='none')}else requestAnimationFrame(update)});window.addEventListener('recorte-grid-change',scheduleSensor);new MutationObserver(()=>requestAnimationFrame(update)).observe(canvas,{attributes:true,attributeFilter:['style','width','height']});setTimeout(rebuild,250)
})();