(()=>{'use strict';if(window.__RECORTE_LINE_LOCK__)return;window.__RECORTE_LINE_LOCK__=true;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let locked=new Set(),selected=null,placeAxis=null;
const key=h=>h?`${h.dataset.axis}:${h.dataset.index}`:'';
function sync(){ $$('.gridHandle').forEach(h=>h.classList.toggle('locked',locked.has(key(h)))); const b=$('#lockSelectedLine');if(b){const on=selected&&locked.has(`${selected.axis}:${selected.index}`);b.textContent=on?'🔒 Destravar linha':'🔓 Travar linha';b.disabled=!selected}}
const row=$('.precisionLineRow');if(row&&!$('#lockSelectedLine')){const b=document.createElement('button');b.id='lockSelectedLine';b.className='secondary';b.disabled=true;b.textContent='🔓 Travar linha';row.appendChild(b);b.addEventListener('click',()=>{if(!selected)return;const k=`${selected.axis}:${selected.index}`;locked.has(k)?locked.delete(k):locked.add(k);sync()})}
document.addEventListener('pointerdown',e=>{const h=e.target.closest?.('.gridHandle');if(!h)return;selected={axis:h.dataset.axis,index:+h.dataset.index};if(locked.has(key(h))){e.preventDefault();e.stopImmediatePropagation()}setTimeout(sync,0)},true);
window.addEventListener('recorte-grid-rebuild',()=>{const c=$('#cols'),r=$('#rows');if(c)c.dispatchEvent(new Event('input',{bubbles:true}));if(r)r.dispatchEvent(new Event('input',{bubbles:true}));locked=new Set([...locked].filter(k=>{const[a,i]=k.split(':');return +i<(a==='x'?+c.value:+r.value)}));setTimeout(sync,40)});
/* placement mode: long press/click button then tap canvas to insert exactly there */
function arm(axis){placeAxis=axis;const msg=$('#linePosition');if(msg)msg.textContent=`Toque na imagem para criar uma linha ${axis==='x'?'vertical':'horizontal'} nessa posição.`;$('#stageWrap')?.classList.add('placingLine')}
$('#addVLine')?.addEventListener('contextmenu',e=>{e.preventDefault();arm('x')});$('#addHLine')?.addEventListener('contextmenu',e=>{e.preventDefault();arm('y')});
const stage=$('#stageWrap'),canvas=$('#canvas');stage?.addEventListener('dblclick',e=>{if(!canvas||canvas.style.display==='none')return;const cr=canvas.getBoundingClientRect();if(e.clientX<cr.left||e.clientX>cr.right||e.clientY<cr.top||e.clientY>cr.bottom)return;const dx=Math.min(e.clientX-cr.left,cr.right-e.clientX),dy=Math.min(e.clientY-cr.top,cr.bottom-e.clientY);placeAxis=dx<dy?'x':'y';insertAt(e)},true);
stage?.addEventListener('pointerdown',e=>{if(!placeAxis)return;insertAt(e);e.preventDefault();e.stopImmediatePropagation()},true);
function insertAt(e){if(!placeAxis||!canvas)return;const cr=canvas.getBoundingClientRect(),axis=placeAxis,norm=axis==='x'?(e.clientX-cr.left)/cr.width:(e.clientY-cr.top)/cr.height;if(norm<=.01||norm>=.99){placeAxis=null;return}const count=Math.max(1,+$(axis==='x'?'#cols':'#rows').value||1),arr=window.recorteGrid?.getLines?.(axis,count)?.slice()||Array.from({length:count+1},(_,i)=>i/count);arr.push(Math.max(.001,Math.min(.999,norm)));arr.sort((a,b)=>a-b);const el=$(axis==='x'?'#cols':'#rows');el.value=arr.length-1;window.recorteGrid?.ensure?.(+$('#cols').value,+$('#rows').value);for(let i=1;i<arr.length-1;i++)window.recorteGrid?.setLine?.(axis,i,arr[i]);window.dispatchEvent(new CustomEvent('recorte-grid-rebuild'));window.recorteSplit?.redraw?.();placeAxis=null;stage.classList.remove('placingLine')}
/* dedicated placement toggles for touch */
if(row&&!$('#placeLineHelp')){const h=document.createElement('div');h.id='placeLineHelp';h.className='info';h.style.gridColumn='1/-1';h.innerHTML='No celular: mantenha pressionado <b>＋ Linha vertical/horizontal</b> para escolher a direção e depois toque no ponto do editor. No PC, duplo clique no editor cria uma linha pelo eixo mais próximo.';row.after(h)}
['addVLine','addHLine'].forEach((id,i)=>{const b=$('#'+id);if(!b)return;let t=null;b.addEventListener('pointerdown',()=>{t=setTimeout(()=>arm(i===0?'x':'y'),520)});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>clearTimeout(t)))})
window.recorteLineLock={isLocked:(axis,index)=>locked.has(`${axis}:${index}`),clear:()=>{locked.clear();sync()}};sync();})();