(()=>{'use strict';if(window.__RECORTE_PRECISION_TOUCH__)return;window.__RECORTE_PRECISION_TOUCH__=true;const $=s=>document.querySelector(s);const stage=$('#stageWrap'),canvas=$('#canvas'),zoom=$('#zoom'),zoomLabel=$('#zoomLabel');if(!stage||!canvas)return;
/* hide legacy padding/gap controls: precision engine owns post-cut margin and never inserts automatic gaps */
const gap=$('#gridGap'),pad=$('#framePadding');if(gap){gap.value='0';gap.disabled=true;const l=gap.closest('label');if(l){l.style.opacity='.45';l.title='Desativado no modo de precisão: não são criados gaps entre cortes.';const t=[...l.childNodes].find(n=>n.nodeType===3);if(t)t.textContent='Gap entre frames (desativado)'}}if(pad){const l=pad.closest('label');if(l)l.style.display='none'}
/* floating exact pixel coordinate while dragging */
let tag=null;function removeTag(){tag?.remove();tag=null}function showTag(h){const im=window.recorteSplit?.getCurrent?.();if(!im||!h)return;const axis=h.dataset.axis,index=+h.dataset.index,count=Math.max(1,+$(axis==='x'?'#cols':'#rows').value||1),arr=window.recorteGrid?.getLines?.(axis,count);if(!arr)return;const px=Math.round(arr[index]*(axis==='x'?(im.naturalWidth||im.width):(im.naturalHeight||im.height)));const r=h.getBoundingClientRect(),sr=stage.getBoundingClientRect();if(!tag){tag=document.createElement('span');tag.className='linePixelTag';stage.appendChild(tag)}tag.textContent=px+' px';tag.style.left=(r.left-sr.left+stage.scrollLeft+r.width/2)+'px';tag.style.top=(r.top-sr.top+stage.scrollTop+(axis==='x'?Math.min(30,r.height/2):r.height/2))+'px'}
document.addEventListener('pointerdown',e=>{const h=e.target.closest?.('.gridHandle');if(h)showTag(h)},true);document.addEventListener('pointermove',e=>{const h=e.target.closest?.('.gridHandle');if(h&&e.buttons)showTag(h)},true);document.addEventListener('pointerup',removeTag,true);document.addEventListener('pointercancel',removeTag,true);
/* two-finger inspection zoom: changes viewport zoom only; no grid coordinate mutation */
let touches=new Map(),pinchStart=null;stage.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){const a=[...touches.values()];pinchStart={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z:+zoom.value||100};e.preventDefault()}}},{capture:true});stage.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'||!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2&&pinchStart){const a=[...touches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),v=Math.max(+zoom.min||10,Math.min(+zoom.max||500,pinchStart.z*d/Math.max(1,pinchStart.d)));zoom.value=Math.round(v);zoom.dispatchEvent(new Event('input',{bubbles:true}));if(zoomLabel)zoomLabel.textContent=Math.round(v)+'%';e.preventDefault();e.stopImmediatePropagation()}},{capture:true,passive:false});function end(e){touches.delete(e.pointerId);if(touches.size<2)pinchStart=null}stage.addEventListener('pointerup',end,true);stage.addEventListener('pointercancel',end,true);
/* exact PDF uses the same mathematical partitions/margin/uniform logic as PNG */
function outputs(){const im=window.recorteSplit?.getCurrent?.();if(!im)return[];const cols=Math.max(1,+$('#cols').value||1),rows=Math.max(1,+$('#rows').value||1),xs=window.recorteGrid?.getLines?.('x',cols)||Array.from({length:cols+1},(_,i)=>i/cols),ys=window.recorteGrid?.getLines?.('y',rows)||Array.from({length:rows+1},(_,i)=>i/rows),W=im.naturalWidth||im.width,H=im.naturalHeight||im.height,m=Math.max(0,+$('#transparentMargin')?.value||0),uniform=!!$('#uniformFrames')?.checked,rs=[];let mw=0,mh=0;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const x0=Math.round(xs[c]*W),x1=Math.round(xs[c+1]*W),y0=Math.round(ys[r]*H),y1=Math.round(ys[r+1]*H),o={sx:x0,sy:y0,sw:Math.max(1,x1-x0),sh:Math.max(1,y1-y0)};mw=Math.max(mw,o.sw+2*m);mh=Math.max(mh,o.sh+2*m);rs.push(o)}return rs.map(o=>{const c=document.createElement('canvas');c.width=uniform?mw:o.sw+2*m;c.height=uniform?mh:o.sh+2*m;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(im,o.sx,o.sy,o.sw,o.sh,Math.round((c.width-o.sw)/2),Math.round((c.height-o.sh)/2),o.sw,o.sh);return c})}
$('#exportPdf')?.addEventListener('click',e=>{if(!window.jspdf?.jsPDF||!window.recorteSplit?.getCurrent?.())return;e.preventDefault();e.stopImmediatePropagation();const cs=outputs();if(!cs.length)return;const {jsPDF}=window.jspdf;const first=cs[0],land=first.width>first.height,pdf=new jsPDF({orientation:land?'landscape':'portrait',unit:'px',format:[first.width,first.height],hotfixes:['px_scaling']});cs.forEach((c,i)=>{if(i)pdf.addPage([c.width,c.height],c.width>c.height?'landscape':'portrait');pdf.addImage(c.toDataURL('image/png'),'PNG',0,0,c.width,c.height,undefined,'FAST')});pdf.save('recorte-split-frames.pdf')},true);
})();