(()=>{'use strict';
const $=s=>document.querySelector(s),dock=$('.previewDock'),wrap=$('#framePreview');if(!dock||!wrap)return;
const style=document.createElement('style');style.textContent=`
.previewPlayer{display:grid;grid-template-columns:minmax(150px,220px) 1fr;gap:12px;align-items:center;margin:10px 0 12px;padding:10px;border:1px solid #25283a;background:#0d0f17;border-radius:12px}.animStage{height:150px;display:grid;place-items:center;background-image:linear-gradient(45deg,#151824 25%,transparent 25%),linear-gradient(-45deg,#151824 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#151824 75%),linear-gradient(-45deg,transparent 75%,#151824 75%);background-size:20px 20px;background-position:0 0,0 10px,10px -10px,-10px 0;border-radius:10px;overflow:hidden}.animStage img{max-width:95%;max-height:95%;object-fit:contain;image-rendering:auto}.playerControls{display:grid;gap:8px}.playerButtons{display:flex;gap:8px;flex-wrap:wrap}.playerButtons button{min-width:42px}.playerSpeed{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;color:#aaa;font-size:11px}.playerMeta{font-size:10px;color:#777}.frameThumb.frameWarning{border-color:#fb7185!important;box-shadow:0 0 0 1px #fb7185 inset,0 0 18px rgba(251,113,133,.16)}.frameThumb .frameWarnBadge{position:absolute;left:5px;top:5px;width:17px;height:17px;border-radius:50%;display:grid;place-items:center;background:#be123c;color:#fff;border:1px solid #fecdd3;font:900 10px/1 system-ui;z-index:3}.frameThumb.playerActive{outline:2px solid #a78bfa;outline-offset:1px}.previewDock .previewHead{gap:10px}@media(max-width:700px){.previewPlayer{grid-template-columns:1fr}.animStage{height:190px}.playerButtons button{flex:1}.playerSpeed{grid-template-columns:auto 1fr 42px}}
`;document.head.appendChild(style);
const player=document.createElement('div');player.className='previewPlayer';player.innerHTML=`<div class="animStage"><img id="animPreviewImg" alt="Preview de animação"></div><div class="playerControls"><div class="playerButtons"><button id="animPrev" class="secondary">‹</button><button id="animPlay" class="primary">▶ Play</button><button id="animNext" class="secondary">›</button><button id="animLoop" class="secondary">Loop: ON</button></div><label class="playerSpeed"><span>Velocidade</span><input id="animSpeed" type="range" min="1" max="20" value="6"><b id="animFps">6 FPS</b></label><div id="animMeta" class="playerMeta">Abra uma imagem para visualizar a sequência.</div></div>`;
const head=$('.previewHead');head?.after(player);
const img=$('#animPreviewImg'),play=$('#animPlay'),prev=$('#animPrev'),next=$('#animNext'),loopBtn=$('#animLoop'),speed=$('#animSpeed'),fps=$('#animFps'),meta=$('#animMeta');
let index=0,timer=null,playing=false,loop=true,warnings=new Set();
function thumbs(){return [...wrap.querySelectorAll('.frameThumb')]}
function stop(){playing=false;clearInterval(timer);timer=null;if(play)play.textContent='▶ Play'}
function show(i){const list=thumbs();if(!list.length){if(img)img.removeAttribute('src');if(meta)meta.textContent='Abra uma imagem para visualizar a sequência.';return}index=Math.max(0,Math.min(list.length-1,i));const item=list[index],src=item.querySelector('img')?.src;if(src&&img)img.src=src;list.forEach((el,j)=>el.classList.toggle('playerActive',j===index));if(meta)meta.textContent=`Frame ${index+1} de ${list.length}${warnings.has(index+1)?' • ⚠ corte atravessa conteúdo':''}`;item.scrollIntoView?.({behavior:'smooth',block:'nearest',inline:'center'})}
function interval(){return Math.max(50,Math.round(1000/(+speed?.value||6)))}
function start(){const list=thumbs();if(!list.length)return;stop();playing=true;if(play)play.textContent='⏸ Pausar';timer=setInterval(()=>{const n=index+1;if(n>=thumbs().length){if(loop)show(0);else stop()}else show(n)},interval())}
play?.addEventListener('click',()=>playing?stop():start());prev?.addEventListener('click',()=>{stop();const l=thumbs().length;show(index<=0?Math.max(0,l-1):index-1)});next?.addEventListener('click',()=>{stop();const l=thumbs().length;show(index>=l-1?0:index+1)});loopBtn?.addEventListener('click',()=>{loop=!loop;loopBtn.textContent=`Loop: ${loop?'ON':'OFF'}`});speed?.addEventListener('input',()=>{if(fps)fps.textContent=`${speed.value} FPS`;if(playing)start()});
wrap.addEventListener('click',e=>{const item=e.target.closest('.frameThumb');if(!item)return;stop();const list=thumbs();show(list.indexOf(item))});
function applyWarnings(){const list=thumbs();list.forEach((item,i)=>{const bad=warnings.has(i+1);item.classList.toggle('frameWarning',bad);let badge=item.querySelector('.frameWarnBadge');if(bad&&!badge){badge=document.createElement('span');badge.className='frameWarnBadge';badge.textContent='!';item.appendChild(badge)}else if(!bad&&badge)badge.remove()});show(Math.min(index,Math.max(0,list.length-1)))}
window.addEventListener('recorte-grid-collisions',e=>{warnings=new Set(e.detail?.frames||[]);applyWarnings()});
const mo=new MutationObserver(()=>{clearTimeout(mo.t);mo.t=setTimeout(()=>{applyWarnings();if(!img?.src)show(0)},60)});mo.observe(wrap,{childList:true,subtree:false});
setTimeout(()=>show(0),400);
})();