(()=>{'use strict';
if(window.__RECORTE_UPLOAD_STABLE_145__)return;window.__RECORTE_UPLOAD_STABLE_145__=true;window.__RECORTE_UPLOAD_CORE_V2__=true;
const $=s=>document.querySelector(s),ACCEPT='image/*,.png,.jpg,.jpeg,.webp,.heic,.heif';
const isImage=file=>!!file&&(file.type?.startsWith('image/')||/\.(png|jpe?g|webp|heic|heif)$/i.test(file.name||''));
const style=document.createElement('style');style.id='recorteUploadStable145';style.textContent=`
.openFile,.heroFile,.upload{position:relative!important}.openFile input.rsStableFile,.heroFile input.rsStableFile,.upload input.rsStableFile{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;display:block!important;opacity:.001!important;z-index:80!important;margin:0!important;padding:0!important;border:0!important;cursor:pointer!important;pointer-events:auto!important;-webkit-appearance:none!important;appearance:none!important;font-size:16px!important}.openFile input.rsStableFile::-webkit-file-upload-button,.heroFile input.rsStableFile::-webkit-file-upload-button,.upload input.rsStableFile::-webkit-file-upload-button{width:100%!important;height:100%!important;opacity:0!important}.upload.rsFileLoading:after{content:'Carregando imagem…';position:absolute;inset:0;z-index:70;display:grid;place-items:center;background:#0b0e15d9;color:#ddd6fe;font:800 11px system-ui;border-radius:inherit;pointer-events:none}
`;document.head.appendChild(style);
function fresh(host,id){if(!host)return null;let old=id?document.getElementById(id):host.querySelector('input[type=file]');let input;if(old){input=old.cloneNode(false);old.replaceWith(input)}else{input=document.createElement('input');input.type='file';host.appendChild(input)}if(id)input.id=id;input.type='file';input.accept=ACCEPT;input.className='rsStableFile';input.removeAttribute('capture');input.removeAttribute('multiple');return input}
const topHost=$('.topActions .openFile')||$('.openFile'),heroHost=$('.heroFile'),areaHost=$('.upload');
const top=fresh(topHost,'fileInput'),hero=fresh(heroHost),area=fresh(areaHost);
const owned=new Set([top,hero,area].filter(Boolean));document.querySelectorAll('input[type=file]').forEach(el=>{if(!owned.has(el))el.remove()});document.querySelectorAll('.rsNativeFileOverlay').forEach(el=>el.remove());
function timeout(p,ms,label){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error(label||'timeout')),ms))])}
function viaImage(file){return new Promise((ok,no)=>{let url;try{url=URL.createObjectURL(file)}catch(e){no(e);return}const im=new Image();let done=false;const finish=(value,err)=>{if(done)return;done=true;try{URL.revokeObjectURL(url)}catch{};err?no(err):ok(value)};im.onload=()=>finish(im);im.onerror=()=>finish(null,new Error('image decode failed'));im.src=url})}
async function viaBitmap(file){if(typeof createImageBitmap!=='function')throw new Error('bitmap unavailable');const b=await createImageBitmap(file),c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);try{b.close?.()}catch{}return c}
function viaReader(file){return new Promise((ok,no)=>{const r=new FileReader();r.onerror=()=>no(r.error||new Error('reader failed'));r.onload=()=>{const im=new Image();im.onload=()=>ok(im);im.onerror=()=>no(new Error('reader image decode failed'));im.src=r.result};r.readAsDataURL(file)})}
async function decode(file){try{return await timeout(viaImage(file),12000,'object url timeout')}catch{}try{return await timeout(viaBitmap(file),12000,'bitmap timeout')}catch{}return await timeout(viaReader(file),15000,'reader timeout')}
function enableEditor(){['aiRemoveBtn','aiProRemoveBtn','autoDetect','applyEdit','exportZip','exportSheet','exportPdf','cropStart','centerImage'].forEach(id=>{const e=document.getElementById(id);if(e)e.disabled=false})}
function setInfo(file,im,ok=true){const box=$('#fileInfo');if(!box)return;box.classList.remove('hidden');if(!ok){box.innerHTML='<div class="fileMeta"><b>Falha ao abrir a imagem</b><span>Tente novamente ou escolha PNG/JPG.</span></div>';return}const w=im.naturalWidth||im.width||0,h=im.naturalHeight||im.height||0;box.innerHTML=`<div class="fileMeta"><b>${file.name||'Imagem'}</b><span>${w}×${h}px · ${(file.size/1048576).toFixed(2)} MB</span></div><div class="alphaBadge ok">✓ Imagem carregada</div>`}
let token=0;async function handle(input){const file=input.files?.[0];if(!isImage(file)){try{input.value=''}catch{};return}const my=++token;areaHost?.classList.add('rsFileLoading');try{const im=await decode(file);if(my!==token)return;if(!window.recorteSplit?.setAIResult)throw new Error('editor não inicializado');window.recorteGrid?.reset?.();window.recorteSplit.setAIResult(im);enableEditor();setInfo(file,im,true);const fmt=$('#format');if(fmt&&/png|webp|heic|heif/i.test((file.type||'')+' '+(file.name||'')))fmt.value='png';window.dispatchEvent(new CustomEvent('recorte-file-loaded',{detail:{name:file.name,width:im.naturalWidth||im.width,height:im.naturalHeight||im.height,stable145:true}}))}catch(err){if(my!==token)return;console.error('Recorte Split upload 1.4.5:',err);setInfo(file,null,false)}finally{if(my===token)areaHost?.classList.remove('rsFileLoading');try{input.value=''}catch{}}}
[top,hero,area].filter(Boolean).forEach(input=>{input.addEventListener('pointerdown',()=>{try{input.value=''}catch{}},{capture:true});input.addEventListener('click',e=>{try{input.value=''}catch{};e.stopPropagation()},{capture:true});input.addEventListener('change',e=>{e.stopImmediatePropagation();handle(input)},{capture:true})});
window.recorteUpload={version:'1.4.5',openTop:()=>top?.click?.(),inputs:()=>[top,hero,area].filter(Boolean)};window.dispatchEvent(new CustomEvent('recorte-upload-ready',{detail:{version:'1.4.5',native:true}}));
})();