(()=>{'use strict';
if(window.__RECORTE_UPLOAD_NATIVE_151__)return;window.__RECORTE_UPLOAD_NATIVE_151__=true;
const VERSION='1.5.1',IMAGE_EXT=/\.(png|jpe?g|webp|heic|heif)$/i,ZIP_EXT=/\.zip$/i,$=s=>document.querySelector(s);
const inputs=[document.getElementById('fileInput'),document.querySelector('.heroFile input[type="file"]')].filter(Boolean);
if(!inputs.length)return;
inputs.forEach((input,i)=>{input.type='file';input.removeAttribute('capture');input.removeAttribute('multiple');input.accept=i===0?'image/*,.png,.jpg,.jpeg,.webp,.heic,.heif,.zip,application/zip':'.zip,application/zip,application/x-zip-compressed,image/*,.png,.jpg,.jpeg,.webp,.heic,.heif';input.setAttribute('aria-label',i===0?'Abrir imagem ou ZIP':'Selecionar arquivo ou ZIP');if(i===1&&!input.id)input.id='fileInputHero';});
const style=document.createElement('style');style.id='rsNative151';style.textContent=`
.openFile,.heroFile{display:flex!important;align-items:center!important;justify-content:center!important;margin-top:0!important;background:transparent!important;border:0!important;box-shadow:none!important}
.openFile>span,.heroFile>span{display:none!important}
.openFile>input[type=file],.heroFile>input[type=file]{display:block!important;position:relative!important;opacity:1!important;visibility:visible!important;pointer-events:auto!important;width:190px!important;max-width:48vw!important;height:42px!important;min-height:42px!important;margin:0!important;padding:0!important;color:#eee9ff!important;background:#17111f!important;border:1px solid #7c3aed!important;border-radius:10px!important;font-size:12px!important;line-height:40px!important;-webkit-appearance:auto!important;appearance:auto!important;-webkit-user-select:auto!important;user-select:auto!important;-webkit-touch-callout:default!important;touch-action:manipulation!important;z-index:100!important}
.heroFile>input[type=file]{width:230px!important;max-width:82vw!important}
.openFile>input[type=file]::file-selector-button,.heroFile>input[type=file]::file-selector-button{height:40px;border:0;border-right:1px solid #7c3aed;background:#6d28d9;color:#fff;font-weight:800;padding:0 12px;margin-right:8px}
.openFile>input[type=file]::-webkit-file-upload-button,.heroFile>input[type=file]::-webkit-file-upload-button{height:40px;border:0;border-right:1px solid #7c3aed;background:#6d28d9;color:#fff;font-weight:800;padding:0 12px;margin-right:8px}
#stageWrap .heroFile,#stageWrap .heroFile *{touch-action:manipulation!important;-webkit-user-select:auto!important;user-select:auto!important;-webkit-touch-callout:default!important}
@media(max-width:430px){.openFile>input[type=file]{width:150px!important;max-width:43vw!important;font-size:10px!important}.heroFile>input[type=file]{width:220px!important;max-width:82vw!important}}
`;document.head.appendChild(style);
function isImage(f){return!!f&&(String(f.type||'').startsWith('image/')||IMAGE_EXT.test(f.name||''))}function isZip(f){return!!f&&(/zip/i.test(String(f.type||''))||ZIP_EXT.test(f.name||''))}
function timeout(p,ms){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('Tempo esgotado ao abrir arquivo.')),ms))])}
function viaURL(file){return new Promise((ok,no)=>{let url;try{url=URL.createObjectURL(file)}catch(e){no(e);return}const im=new Image();im.onload=()=>{try{URL.revokeObjectURL(url)}catch{};ok(im)};im.onerror=()=>{try{URL.revokeObjectURL(url)}catch{};no(new Error('Falha ao decodificar imagem.'))};im.src=url})}
async function viaBitmap(file){if(typeof createImageBitmap!=='function')throw new Error('createImageBitmap indisponível');const b=await createImageBitmap(file),c=document.createElement('canvas');c.width=b.width;c.height=b.height;c.getContext('2d',{alpha:true}).drawImage(b,0,0);try{b.close?.()}catch{}return c}
function viaReader(file){return new Promise((ok,no)=>{const r=new FileReader();r.onerror=()=>no(r.error||new Error('Falha no FileReader'));r.onload=()=>{const im=new Image();im.onload=()=>ok(im);im.onerror=()=>no(new Error('Falha ao abrir DataURL'));im.src=r.result};r.readAsDataURL(file)})}
async function decode(file){try{return await timeout(viaURL(file),15000)}catch{}try{return await timeout(viaBitmap(file),15000)}catch{}return timeout(viaReader(file),20000)}
async function fromZip(file){if(!window.JSZip)throw new Error('Leitor ZIP ainda não carregou.');const zip=await window.JSZip.loadAsync(file),entries=Object.values(zip.files).filter(e=>!e.dir&&IMAGE_EXT.test(e.name||'')).sort((a,b)=>String(a.name).localeCompare(String(b.name),undefined,{numeric:true}));if(!entries.length)throw new Error('O ZIP não contém PNG, JPG, WEBP, HEIC ou HEIF.');const entry=entries[0],blob=await entry.async('blob'),name=(entry.name||'imagem.png').split('/').pop();let f;try{f=new File([blob],name,{type:/\.png$/i.test(name)?'image/png':/\.jpe?g$/i.test(name)?'image/jpeg':/\.webp$/i.test(name)?'image/webp':''})}catch{f=blob;try{Object.defineProperty(f,'name',{value:name})}catch{}}return{file:f,name,total:entries.length}}
function enable(){['aiRemoveBtn','aiProRemoveBtn','autoDetect','applyEdit','exportZip','exportSheet','exportPdf','cropStart','centerImage'].forEach(id=>{const e=document.getElementById(id);if(e)e.disabled=false})}
function status(title,sub,error=false){const b=$('#fileInfo');if(!b)return;b.classList.remove('hidden');b.innerHTML=`<div class="fileMeta"><b>${title}</b><span>${sub||''}</span></div>`;b.classList.toggle('error',error)}
let seq=0;async function handle(input){const original=input.files?.[0];if(!original)return;const mine=++seq;try{let target=original,zipMeta=null;if(isZip(original)){status('Abrindo ZIP…','Processando no dispositivo');zipMeta=await fromZip(original);target=zipMeta.file}else if(!isImage(original))throw new Error('Escolha uma imagem ou ZIP.');else status('Abrindo imagem…','Processando no dispositivo');const im=await decode(target);if(mine!==seq)return;if(!window.recorteSplit?.setAIResult)throw new Error('Editor ainda não carregou completamente.');window.recorteGrid?.reset?.();window.recorteSplit.setAIResult(im);enable();const w=im.naturalWidth||im.width||0,h=im.naturalHeight||im.height||0;status(zipMeta?zipMeta.name:(original.name||'Imagem'),zipMeta?`ZIP com ${zipMeta.total} imagem(ns) · ${w}×${h}px`:`${w}×${h}px`);window.dispatchEvent(new CustomEvent('recorte-file-loaded',{detail:{name:original.name,width:w,height:h,fromZip:!!zipMeta,version:VERSION}}))}catch(err){console.error('Recorte Split upload '+VERSION,err);status('Não foi possível abrir',err?.message||'Formato não suportado',true)}finally{try{input.value=''}catch{}}}
inputs.forEach(input=>{input.addEventListener('change',e=>{e.stopImmediatePropagation();handle(input)},{capture:true});input.addEventListener('cancel',()=>{try{input.value=''}catch{}})});
window.recorteUpload={version:VERSION,inputs:()=>inputs,native:true,zip:true,noProgrammaticClick:true};window.dispatchEvent(new CustomEvent('recorte-upload-ready',{detail:{version:VERSION,native:true,zip:true,noProgrammaticClick:true}}));
})();