(()=>{'use strict';
const $=s=>document.querySelector(s),stage=$('#stageWrap'),canvas=$('#canvas'),zoom=$('#zoom'),zoomLabel=$('#zoomLabel');if(!stage||!canvas||!zoom)return;
const style=document.createElement('style');style.textContent=`
.viewLockBtn{height:34px;padding:0 11px;border-radius:9px;border:1px solid #34374a;background:#10131d;color:#c5c7d1;font:700 11px system-ui;white-space:nowrap}.viewLockBtn.active{border-color:#8b5cf6;background:#23133d;color:#eadfff;box-shadow:0 0 0 1px #7c3aed55 inset}.viewLockBtn .dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#6b7280;margin-right:6px;vertical-align:1px}.viewLockBtn.active .dot{background:#a78bfa;box-shadow:0 0 8px #a78bfa}.viewZoomHint{font-size:9px;color:#8f92a3;white-space:nowrap}.viewLockedCanvas{will-change:transform;transition:transform .04s linear}.viewPanActive{cursor:grab!important;overscroll-behavior:contain}.viewPanActive.panning{cursor:grabbing!important}.viewPanActive #canvas{touch-action:none}@media(max-width:760px){.viewLockBtn{height:32px;padding:0 9px;font-size:10px}.viewZoomHint{display:none}}
`;document.head.appendChild(style);
const box=$('.zoomBox'),btn=document.createElement('button');btn.type='button';btn.className='viewLockBtn';btn.id='viewLockBtn';btn.innerHTML='<span class="dot"></span>Fixar foto';box?.prepend(btn);const hint=document.createElement('span');hint.className='viewZoomHint';hint.textContent='Zoom da imagem';box?.append(hint);
let locked=false,inspect=1,sourceZoom=1,pan=null;
function notify(){requestAnimationFrame(()=>{window.dispatchEvent(new CustomEvent('recorte-grid-change'));window.dispatchEvent(new Event('resize'))})}
function apply(){canvas.classList.toggle('viewLockedCanvas',locked);stage.classList.toggle('viewPanActive',locked);canvas.style.transform=locked?`scale(${inspect})`:'';canvas.style.transformOrigin='0 0';stage.style.overflow=locked&&inspect>1?'auto':'';stage.style.touchAction=locked?'none':'';notify()}
function setInspect(v,anchor=true){const old=inspect;inspect=Math.max(.5,Math.min(5,+v||1));if(anchor&&locked&&old>0){const cx=stage.scrollLeft+stage.clientWidth/2,cy=stage.scrollTop+stage.clientHeight/2,ratio=inspect/old;requestAnimationFrame(()=>{stage.scrollLeft=Math.max(0,cx*ratio-stage.clientWidth/2);stage.scrollTop=Math.max(0,cy*ratio-stage.clientHeight/2);notify()})}zoom.value=Math.round(inspect*100);if(zoomLabel)zoomLabel.textContent=Math.round(inspect*100)+'%';apply()}
function toggle(){locked=!locked;btn.classList.toggle('active',locked);btn.innerHTML=locked?'<span class="dot"></span>Foto fixa':'<span class="dot"></span>Fixar foto';if(locked){sourceZoom=window.recorteSplit?.getViewState?.().scale||1;inspect=1;zoom.min=50;zoom.max=500;zoom.value=100;if(zoomLabel)zoomLabel.textContent='100%';hint.textContent='Arraste para navegar';stage.scrollLeft=0;stage.scrollTop=0}else{pan=null;stage.classList.remove('panning');canvas.style.transform='';stage.style.overflow='';stage.style.touchAction='';stage.scrollLeft=0;stage.scrollTop=0;zoom.min=10;zoom.max=500;zoom.value=Math.round(sourceZoom*100);if(zoomLabel)zoomLabel.textContent=Math.round(sourceZoom*100)+'%';hint.textContent='Zoom da imagem';zoom.dispatchEvent(new Event('input',{bubbles:true}))}apply()}
btn.addEventListener('click',toggle);
document.addEventListener('input',e=>{if(!locked||e.target!==zoom)return;e.stopImmediatePropagation();e.preventDefault();setInspect((+zoom.value||100)/100)},true);
stage.addEventListener('wheel',e=>{if(!locked)return;e.preventDefault();e.stopImmediatePropagation();setInspect(inspect*(e.deltaY<0?1.1:.9))},{capture:true,passive:false});
function canPanTarget(t){return !t.closest?.('.gridHandle,.cropEditorLayer,button,input,select,label,a,.frameThumb')}
stage.addEventListener('pointerdown',e=>{if(!locked||!canPanTarget(e.target))return;pan={id:e.pointerId,x:e.clientX,y:e.clientY,left:stage.scrollLeft,top:stage.scrollTop};stage.classList.add('panning');stage.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopImmediatePropagation()},{capture:true});
stage.addEventListener('pointermove',e=>{if(!locked||!pan||pan.id!==e.pointerId)return;stage.scrollLeft=Math.max(0,pan.left-(e.clientX-pan.x));stage.scrollTop=Math.max(0,pan.top-(e.clientY-pan.y));notify();e.preventDefault();e.stopImmediatePropagation()},{capture:true});
function endPan(e){if(!pan||pan.id!==e.pointerId)return;pan=null;stage.classList.remove('panning');try{stage.releasePointerCapture?.(e.pointerId)}catch{}notify();e.preventDefault();e.stopImmediatePropagation()}
stage.addEventListener('pointerup',endPan,{capture:true});stage.addEventListener('pointercancel',endPan,{capture:true});
stage.addEventListener('scroll',()=>{if(locked)notify()},{passive:true});
window.addEventListener('recorte-crop-mode',()=>{if(locked)apply()});
window.recorteViewport={isLocked:()=>locked,getInspectZoom:()=>inspect,isPanning:()=>!!pan};
})();